image: mcr.microsoft.com/playwright:v1.44.1-jammy

stages:
  - mirror

mirror_to_github:
  stage: mirror
  only:
    - main
  script:
    - mkdir -p ~/.ssh
    - echo "$GIT_SSH_PRIVATE_KEY" > ~/.ssh/id_ed25519
    - chmod 600 ~/.ssh/id_ed25519
    - ssh-keyscan github.com >> ~/.ssh/known_hosts
    - git config --global user.name "developer-elgentos"
    - git config --global user.email "developer@elgentos.io"
    - git remote add github git@github.com:elgentos/magento2-playwright.git
    - git push github HEAD:main

test_mirror_pipeline:
  stage: mirror
  rules:
    - if: '$CI_COMMIT_BRANCH != "main"'
  script:
    - mkdir -p ~/.ssh
    - printf "%s\n" "$GIT_SSH_PRIVATE_KEY" > ~/.ssh/id_ed25519
    - chmod 600 ~/.ssh/id_ed25519
    - ssh-keyscan github.com >> ~/.ssh/known_hosts
    - git config --global user.name "developer-elgentos"
    - git config --global user.email "developer@elgentos.io"
    - git ls-remote git@github.com:elgentos/magento2-playwright.git
