name: Auto merge GitLab branch

on:
  push:
    branches:
      - gitlab-main

jobs:
  create-pr-and-merge:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v7
        with:
          branch: gitlab-main
          base: main
          title: "Sync gitlab-main to main"
          body: "Automated PR from GitLab CI mirror."
          token: ${{ secrets.GITHUB_TOKEN }}
          draft: false

      - name: Auto-merge PR
        uses: pascalgn/automerge-action@v0.16.4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
