name: Sync gitlab-main to main via gh CLI

on:
  push:
    branches:
      - gitlab-main

jobs:
  pr-and-merge:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Authenticate GitHub CLI
        run: gh auth setup-git
        env:
          GH_TOKEN: ${{ secrets.AUTOMERGE_TOKEN }}

      - name: Check or create PR
        id: pr
        env:
          GH_TOKEN: ${{ secrets.AUTOMERGE_TOKEN }}
        run: |
          set -e
          pr_number=$(gh pr list --head gitlab-main --base main --state open --json number -q '.[0].number')
          
          if [ -z "$pr_number" ]; then
            echo "No PR found. Creating new PR..."
            gh pr create \
              --head gitlab-main \
              --base main \
              --title "Sync gitlab-main to main" \
              --body "Automated PR from GitLab CI via gh CLI" \
              --label auto-merge
          
            # PR is just created; get number again
            pr_number=$(gh pr list --head gitlab-main --base main --state open --json number -q '.[0].number')
          else
            echo "PR already exists with number: $pr_number"
          fi
          
          echo "pr_number=$pr_number" >> "$GITHUB_OUTPUT"

      - name: Approve PR
        env:
          GH_TOKEN: ${{ secrets.AUTOAPPROVE_TOKEN }}
        run: |
          PR_NUMBER="${{ steps.pr.outputs.pr_number }}"
          gh pr review "$PR_NUMBER" --approve

      - name: Merge PR with gh CLI
        env:
          GH_TOKEN: ${{ secrets.AUTOMERGE_TOKEN }}
        run: |
          PR_NUMBER="${{ steps.pr.outputs.pr_number }}"
          gh pr merge "$PR_NUMBER" --merge --admin
